import fs from 'fs';

const original = fs.readFileSync('C:\\Users\\eltig\\AppData\\Local\\Temp\\kilo\\migrations_original/20260810000004_seed_timetable_data.sql', 'utf8');

// Find the rooms section in the original
const roomsInsertStart = original.indexOf('INSERT INTO public.rooms');
const onConflictStart = original.indexOf('ON CONFLICT (id) DO UPDATE SET', roomsInsertStart);
const onConflictEnd = original.indexOf('\n\n', onConflictStart);
const afterRooms = original.substring(onConflictEnd);

// Read the converted 160 rooms from the file generated by convert-rooms.ts
const converted = fs.readFileSync('supabase/migrations/20260810000004_seed_timetable_data.sql', 'utf8');
const convertedRoomsEnd = converted.indexOf('ON CONFLICT (id) DO UPDATE SET');
const convertedRoomsSection = converted.substring(0, convertedRoomsEnd);

// Build new rooms section: converted rooms without IDs in VALUES
let roomsInsertWithoutId = convertedRoomsSection.replace(
  'INSERT INTO public.rooms (id, name, building, floor, room_number, capacity, room_type, campus, accessibility, equipment, status, notes)\nVALUES\n',
  'INSERT INTO public.rooms (name, building, floor, room_number, capacity, room_type, campus, accessibility, equipment, status, notes)\nVALUES\n'
);

// Remove IDs from each row
const roomsLines = roomsInsertWithoutId.split('\n');
const fixedRoomsLines = roomsLines.map(line => {
  const trimmed = line.trim();
  if (trimmed.startsWith("('") && trimmed.includes("', '")) {
    return line.replace(/\s*\('[^']*',\s*/, '  (');
  }
  return line;
});
const fixedRoomsSection = fixedRoomsLines.join('\n') + '\nON CONFLICT (id) DO UPDATE SET\n  name = EXCLUDED.name,\n  building = EXCLUDED.building,\n  capacity = EXCLUDED.capacity,\n  room_type = EXCLUDED.room_type,\n  status = EXCLUDED.status;\n\n';

// Build the complete seed file
let completeSeed = fixedRoomsSection + afterRooms;

// Fix course_section_meetings room references
completeSeed = completeSeed.replace(
  "CASE WHEN cs.delivery_mode = 'ONLINE' THEN 'r012-1111-1111-1111' ELSE 'r001-1111-1111-1111' END,",
  "CASE WHEN cs.delivery_mode = 'ONLINE' THEN (SELECT id FROM public.rooms WHERE room_type = 'COMPUTER_LAB' ORDER BY random() LIMIT 1) ELSE (SELECT id FROM public.rooms WHERE room_type = 'LECTURE_ROOM' ORDER BY random() LIMIT 1) END,"
);

fs.writeFileSync('supabase/migrations/20260810000004_seed_timetable_data.sql', completeSeed);
console.log('Wrote complete seed file');

// Verify
const verify = fs.readFileSync('supabase/migrations/20260810000004_seed_timetable_data.sql', 'utf8');
const firstRoom = verify.match(/INSERT INTO public\.rooms[\s\S]*?VALUES\n\s*\(/);
console.log('First room:', firstRoom ? firstRoom[0].substring(0, 100) : 'not found');
const onConflictCount = (verify.match(/ON CONFLICT \(id\) DO UPDATE SET/g) || []).length;
console.log('ON CONFLICT count:', onConflictCount);
const meetingCase = verify.match(/CASE WHEN cs\.delivery_mode[^\n]+/);
console.log('Meeting case:', meetingCase ? meetingCase[0] : 'not found');
const lineCount = verify.split('\n').length;
console.log('Total lines:', lineCount);
