import fs from 'fs';

const originalSeed = fs.readFileSync('C:\\Users\\eltig\\AppData\\Local\\Temp\\kilo\\migrations_original/20260810000004_seed_timetable_data.sql', 'utf8');

// Read the converted rooms from the file generated by convert-rooms.ts
const convertScript = fs.readFileSync('scripts/convert-rooms.ts', 'utf8');
const inputMatch = convertScript.match(/const input = `([\s\S]*?)`;/);
if (!inputMatch) {
  console.log('Could not find input in convert-rooms.ts');
  process.exit(1);
}
const inputData = inputMatch[1];

const roomTypeMap = {
  'Lecture Hall': 'LECTURE_ROOM',
  'Lecture Theatre': 'LECTURE_ROOM',
  'Classroom': 'LECTURE_ROOM',
  'Computer Classroom': 'COMPUTER_LAB',
  'Computer Lab': 'COMPUTER_LAB',
  'Simulation Lab': 'SPECIALIZED_ROOM',
  'Studio': 'SPECIALIZED_ROOM',
  'Art Studio': 'SPECIALIZED_ROOM',
  'Specialized Studio': 'SPECIALIZED_ROOM',
  'Audio Lab': 'SPECIALIZED_ROOM',
  'Design Studio': 'SPECIALIZED_ROOM',
  'Media Studio': 'SPECIALIZED_ROOM',
  'Photography Studio': 'SPECIALIZED_ROOM',
  'Film Studio': 'SPECIALIZED_ROOM',
  'Workshop': 'SPECIALIZED_ROOM',
  'Research Room': 'SEMINAR_ROOM',
  'Collaboration Room': 'SEMINAR_ROOM',
  'Seminar Room': 'SEMINAR_ROOM',
  'Science Laboratory': 'SCIENCE_LAB',
  'Chemistry Laboratory': 'SCIENCE_LAB',
  'Physics Laboratory': 'SCIENCE_LAB',
  'Microbiology Laboratory': 'SCIENCE_LAB',
  'Biochemistry Laboratory': 'SCIENCE_LAB',
  'Clinical Laboratory': 'CLINICAL_LAB',
  'Medical Laboratory': 'CLINICAL_LAB',
  'Clinical Skills Lab': 'CLINICAL_LAB',
  'Training Kitchen': 'SPECIALIZED_ROOM',
  'Food Laboratory': 'SPECIALIZED_ROOM',
  'Practical Laboratory': 'SPECIALIZED_ROOM',
  'Teaching Lab': 'SPECIALIZED_ROOM',
  'Specialized Lab': 'SPECIALIZED_ROOM',
  'Research Laboratory': 'SPECIALIZED_ROOM',
  'Cybersecurity Lab': 'COMPUTER_LAB',
  'Specialized Laboratory': 'SPECIALIZED_ROOM',
  'Training Room': 'SEMINAR_ROOM',
  'Practicum Room': 'SEMINAR_ROOM',
  'Simulation Room': 'SPECIALIZED_ROOM',
  'Preparation Room': 'SPECIALIZED_ROOM',
  'Design Lab': 'COMPUTER_LAB',
  'Innovation Lab': 'SPECIALIZED_ROOM',
  'Robotics Lab': 'SPECIALIZED_ROOM',
  'Electronics Lab': 'SPECIALIZED_ROOM',
  'Demonstration Room': 'SPECIALIZED_ROOM',
  'Case Study Room': 'SEMINAR_ROOM',
  'Media Seminar Room': 'SEMINAR_ROOM',
};

function normalizeEquipment(equip) {
  if (!equip || equip === '{}') return '{}';
  const items = equip.split(';').map(s => s.trim()).filter(Boolean);
  const obj = {};
  for (const item of items) {
    const key = item.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
    obj[key] = true;
  }
  return JSON.stringify(obj);
}

const valuesMatch = inputData.match(/VALUES\s*([\s\S]*?);$/);
if (!valuesMatch) {
  console.log('Could not parse VALUES section');
  process.exit(1);
}
const valuesText = valuesMatch[1];
const rows = [];
const rowRegex = /\('([^']*)','([^']*)','([^']*)',(\d+),'([^']*)',(\d+),'([^']*)','([^']*)',(true|false),'([^']*)','([^']*)','([^']*)'\)/g;
let match;
while ((match = rowRegex.exec(valuesText)) !== null) {
  rows.push({
    id: match[1],
    name: match[2],
    building: match[3],
    floor: match[4],
    room_number: match[5],
    capacity: parseInt(match[6]),
    room_type: match[7],
    campus: match[8],
    accessibility: match[9],
    equipment: match[10],
    status: match[11],
    notes: match[12],
  });
}

console.log(`Parsed ${rows.length} rooms`);

const outputRows = rows.map(r => {
  const mappedType = roomTypeMap[r.room_type] || 'SPECIALIZED_ROOM';
  const equipment = normalizeEquipment(r.equipment);
  return `  ('${r.name.replace(/'/g, "''")}', '${r.building.replace(/'/g, "''")}', '${r.floor}', '${r.room_number}', ${r.capacity}, '${mappedType}', 'MAIN', ${r.accessibility}, '${equipment}', 'ACTIVE', '${r.notes.replace(/'/g, "''")}')`;
}).join(',\n');

const roomsSection = `INSERT INTO public.rooms (name, building, floor, room_number, capacity, room_type, campus, accessibility, equipment, status, notes)
VALUES
${outputRows}
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  building = EXCLUDED.building,
  capacity = EXCLUDED.capacity,
  room_type = EXCLUDED.room_type,
  status = EXCLUDED.status;
`;

const originalRoomsInsertStart = originalSeed.indexOf('INSERT INTO public.rooms');
const originalOnConflictStart = originalSeed.indexOf('ON CONFLICT (id) DO UPDATE SET', originalRoomsInsertStart);
const originalAfterRooms = originalSeed.substring(originalSeed.indexOf('\n\n', originalOnConflictStart));

let completeSeed = roomsSection + '\n\n' + originalAfterRooms;

// Fix course_section_meetings room references
completeSeed = completeSeed.replace(
  "CASE WHEN cs.delivery_mode = 'ONLINE' THEN 'r012-1111-1111-1111' ELSE 'r001-1111-1111-1111' END,",
  "CASE WHEN cs.delivery_mode = 'ONLINE' THEN (SELECT id FROM public.rooms WHERE room_type = 'COMPUTER_LAB' ORDER BY random() LIMIT 1) ELSE (SELECT id FROM public.rooms WHERE room_type = 'LECTURE_ROOM' ORDER BY random() LIMIT 1) END,"
);

// Remove hardcoded IDs from other INSERT statements that use UUID columns
// room_features: remove id column and values
completeSeed = completeSeed.replace(
  'INSERT INTO public.room_features (id, name, description, category) VALUES\n  (\'f001-1111-1111-1111\', \'projector\', \'Video projector\', \'AV\'),\n  (\'f002-1111-1111-1111\', \'smart_board\', \'Interactive smart board\', \'AV\'),\n  (\'f003-1111-1111-1111\', \'computers\', \'Desktop computers\', \'COMPUTING\'),\n  (\'f004-1111-1111-1111\', \'science_lab\', \'Science lab equipment\', \'SCIENCE\'),\n  (\'f005-1111-1111-1111\', \'nursing_equipment\', \'Nursing clinical equipment\', \'MEDICAL\'),\n  (\'f006-1111-1111-1111\', \'audio_visual\', \'Audio visual system\', \'AV\'),\n  (\'f007-1111-1111-1111\', \'wheelchair_access\', \'Wheelchair accessible\', \'ACCESSIBILITY\'),\n  (\'f008-1111-1111-1111\', \'specialized_equipment\', \'Specialized equipment\', \'GENERAL\')\nON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description, category = EXCLUDED.category;',
  'INSERT INTO public.room_features (name, description, category) VALUES\n  (\'projector\', \'Video projector\', \'AV\'),\n  (\'smart_board\', \'Interactive smart board\', \'AV\'),\n  (\'computers\', \'Desktop computers\', \'COMPUTING\'),\n  (\'science_lab\', \'Science lab equipment\', \'SCIENCE\'),\n  (\'nursing_equipment\', \'Nursing clinical equipment\', \'MEDICAL\'),\n  (\'audio_visual\', \'Audio visual system\', \'AV\'),\n  (\'wheelchair_access\', \'Wheelchair accessible\', \'ACCESSIBILITY\'),\n  (\'specialized_equipment\', \'Specialized equipment\', \'GENERAL\')\nON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description, category = EXCLUDED.category;'
);

fs.writeFileSync('supabase/migrations/20260810000004_seed_timetable_data.sql', completeSeed);
console.log('Wrote complete seed file');

// Verify
const verify = fs.readFileSync('supabase/migrations/20260810000004_seed_timetable_data.sql', 'utf8');
const firstRoom = verify.match(/INSERT INTO public\.rooms[\s\S]*?VALUES\n\s*\(/);
console.log('First room:', firstRoom ? firstRoom[0].substring(0, 120) : 'not found');
const onConflictCount = (verify.match(/ON CONFLICT \(id\) DO UPDATE SET/g) || []).length;
console.log('ON CONFLICT count:', onConflictCount);
const meetingCase = verify.match(/CASE WHEN cs\.delivery_mode[^\n]+/);
console.log('Meeting case:', meetingCase ? meetingCase[0] : 'not found');
const roomFeatures = verify.match(/INSERT INTO public\.room_features[\s\S]*?ON CONFLICT/);
console.log('Room features:', roomFeatures ? roomFeatures[0].substring(0, 80) : 'not found');
const roomFeatureAssignments = verify.match(/INSERT INTO public\.room_feature_assignments[\s\S]*?ON CONFLICT/);
console.log('Room feature assignments:', roomFeatureAssignments ? roomFeatureAssignments[0].substring(0, 80) : 'not found');
